### ISSUE TITLE
pal2nal nor the Docker image is distributable due to lack of license

### ISSUE THREAD

**Issue by mr-c** [fstrozzi/scalability-reproducibility-chapter#1]
Has anyone contacted Mikita Suyama?

**Comment by mr-c** [comment]
I emailed, but mikita@genome.med.kyoto-u.ac.jp bounces

**Comment by fstrozzi** [comment]
Thanks for pointing that out! The lack of license could be an issue,
although the software package itself is marked as "distribution version" on
the Peer Bork website and there are no known restrictions to use according
to Omics Tools database :https://omictools.com/pal2nal-tool

I will report this to the packaging team so that they can double check.



Le lun. 9 oct. 2017 à 15:35, Michael R. Crusoe <notifications@github.com> a
écrit :

**Comment by mr-c** [comment]
@fstrozzi Thanks. Alas "no known restrictions" doesn't equate to "free to distribute". Gotta have a license :-)

**Comment by pjotrp** [comment]
I wrote a version once at https://github.com/pjotrp/bioruby-alignment/blob/master/lib/bio-alignment/pal2nal.rb 

I'll test it.

**Comment by fstrozzi** [comment]
Got words back from Prof. Mikita, he agreed to clarify the license of the software and he'll update PAL2NAL with a GPL license in the next week. So we should be fine with that. I'm leaving the issue open until we receive an updated version of the script which includes the license.

**Comment by mr-c** [comment]
@fstrozzi Awesome news, please send thanks from myself & DebianMed!

**Comment by pjotrp** [comment]
We also have my alternative: https://github.com/fstrozzi/scalability-reproducibility-chapter/issues/2

**Comment by fstrozzi** [comment]
@pjotrp good to know 👍

**Comment by pjotrp** [comment]
Actual code is here. Short and sweet. https://github.com/pjotrp/bioruby-alignment/blob/master/bin/pal2nal#L108

**Comment by fstrozzi** [comment]
I have received the new version of the Pal2Nal script that is now released under GPL v2. This repository and the Docker container have been updated to include the new script. 

Prof. Mikita will also update the downloadable version from the EMBL site in the next days. So I am closing this issue now.
